sudo: required
services:
    - docker

before_install:
    - docker build -t kevinsp/react-test -f ./client/Dockerfile.dev ./client


script:
    - docker run kevinsp/react-test npm test -- --coverage

after_success: 

    - docker build -t kevinsp/multi-client ./client
   
    - docker build -t kevinsp/multi-nginx ./nginx

    - docker build -t kevinsp/multi-server ./server

    - docker build -t kevinsp/multi-worker ./worker

      ##log into docker cli

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

      ##take those images AND PUUUUSHH to da DOKAH HUBB
      #
    - docker push kevinsp/multi-client
    - docker push kevinsp/multi-nginx
    - docker push kevinsp/multi-server
    - docker push kevinsp/multi-worker
